/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: hJoSVHfSimLd0PAfxYlgCMDXUeDwTMdCRdTuUvrZkTSuSMowYLY98/CBUgfdBresvEmRrmKIWLxCBK79FA+ntQ==
 */

/* eslint-disable */
// tslint:disable

import Week from './week'

interface Band {
  /**
   * @default 0
   */
  buzz: number
  color_dark: string
  color_light: string
  /**
   * @default nextval('band_id_seq'::regclass)
   */
  id: number & {readonly __brand?: 'band_id'}
  /**
   * @default 1
   */
  level: number
  name: string
  /**
   * @default 1
   */
  start_level: number
  start_week_id: Week['id']
}
export default Band;

interface Band_InsertParameters {
  /**
   * @default 0
   */
  buzz?: number
  color_dark: string
  color_light: string
  /**
   * @default nextval('band_id_seq'::regclass)
   */
  id?: number & {readonly __brand?: 'band_id'}
  /**
   * @default 1
   */
  level?: number
  name: string
  /**
   * @default 1
   */
  start_level?: number
  start_week_id: Week['id']
}
export type {Band_InsertParameters}
