/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: hpKWYcJHXuBEIfjnK8na5nahoAha5JLQK5fDLHX67MXfmgK2b0VSe0Bn6lliRI8zAsUbkq9p6XEZFY2CqCGKlQ==
 */

/* eslint-disable */
// tslint:disable

import Week from './week'

interface Band {
  /**
   * @default 0
   */
  buzz: number
  color_dark: string
  color_light: string
  /**
   * @default nextval('band_id_seq'::regclass)
   */
  id: number & {readonly __brand?: 'band_id'}
  /**
   * @default 1
   */
  level: number
  name: string
  retire_week_id: (Week['id']) | null
  /**
   * @default 1
   */
  start_level: number
  start_week_id: Week['id']
  tags: string
}
export default Band;

interface Band_InsertParameters {
  /**
   * @default 0
   */
  buzz?: number
  color_dark: string
  color_light: string
  /**
   * @default nextval('band_id_seq'::regclass)
   */
  id?: number & {readonly __brand?: 'band_id'}
  /**
   * @default 1
   */
  level?: number
  name: string
  retire_week_id?: (Week['id']) | null
  /**
   * @default 1
   */
  start_level?: number
  start_week_id: Week['id']
  tags: string
}
export type {Band_InsertParameters}
