/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: t1xTvAAwH5uHJxvllPiLECfz2PsXNeYKzg+tT1Kv+ug5aBgsFUYx37JEQC+gxSCEwsbs2ZvBZrN0fiCeHrKjcA==
 */

/* eslint-disable */
// tslint:disable

import Week from './week'

interface Battle {
  /**
   * @default nextval('battle_id_seq'::regclass)
   */
  id: number & {readonly __brand?: 'battle_id'}
  level: number
  week_id: Week['id']
}
export default Battle;

interface Battle_InsertParameters {
  /**
   * @default nextval('battle_id_seq'::regclass)
   */
  id?: number & {readonly __brand?: 'battle_id'}
  level: number
  week_id: Week['id']
}
export type {Battle_InsertParameters}
