/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: PB8FEHWKkSBkvUNwW+35zMFuA36dkXNGx1NBnYluv9o9QABKaJNB4OaUP46zH64IqC8yyU1QrLfwQsir7rsSOQ==
 */

/* eslint-disable */
// tslint:disable

import AtdatabasesMigrationsApplied, {AtdatabasesMigrationsApplied_InsertParameters} from './atdatabases_migrations_applied'
import AtdatabasesMigrationsVersion, {AtdatabasesMigrationsVersion_InsertParameters} from './atdatabases_migrations_version'
import Band, {Band_InsertParameters} from './band'
import Battle, {Battle_InsertParameters} from './battle'
import Entry, {Entry_InsertParameters} from './entry'
import Performance, {Performance_InsertParameters} from './performance'
import Song, {Song_InsertParameters} from './song'
import Week, {Week_InsertParameters} from './week'
import WeeklyBuzz, {WeeklyBuzz_InsertParameters} from './weekly_buzz'

interface DatabaseSchema {
  atdatabases_migrations_applied: {record: AtdatabasesMigrationsApplied, insert: AtdatabasesMigrationsApplied_InsertParameters};
  atdatabases_migrations_version: {record: AtdatabasesMigrationsVersion, insert: AtdatabasesMigrationsVersion_InsertParameters};
  band: {record: Band, insert: Band_InsertParameters};
  battle: {record: Battle, insert: Battle_InsertParameters};
  entry: {record: Entry, insert: Entry_InsertParameters};
  performance: {record: Performance, insert: Performance_InsertParameters};
  song: {record: Song, insert: Song_InsertParameters};
  week: {record: Week, insert: Week_InsertParameters};
  weekly_buzz: {record: WeeklyBuzz, insert: WeeklyBuzz_InsertParameters};
}
export default DatabaseSchema;

function serializeValue(_tableName: string, _columnName: string, value: unknown): unknown {
  return value;
}
export {serializeValue}

export type {
  AtdatabasesMigrationsApplied,
  AtdatabasesMigrationsApplied_InsertParameters,
  AtdatabasesMigrationsVersion,
  AtdatabasesMigrationsVersion_InsertParameters,
  Band,
  Band_InsertParameters,
  Battle,
  Battle_InsertParameters,
  Entry,
  Entry_InsertParameters,
  Performance,
  Performance_InsertParameters,
  Song,
  Song_InsertParameters,
  Week,
  Week_InsertParameters,
  WeeklyBuzz,
  WeeklyBuzz_InsertParameters,
}
