/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: FX6hL4q5ii0586w0bedcP6swqUZgX7+V3OJzn/eUafqfSBS+Vc1h5NSi48wTtGRFxC0HzdeH9YlI8C22s5gfWA==
 */

/* eslint-disable */
// tslint:disable

import AtdatabasesMigrationsApplied, {AtdatabasesMigrationsApplied_InsertParameters} from './atdatabases_migrations_applied'
import AtdatabasesMigrationsVersion, {AtdatabasesMigrationsVersion_InsertParameters} from './atdatabases_migrations_version'
import Band, {Band_InsertParameters} from './band'
import Battle, {Battle_InsertParameters} from './battle'
import Entry, {Entry_InsertParameters} from './entry'
import MbGenre, {MbGenre_InsertParameters} from './mb_genre'
import MbGenreAlias, {MbGenreAlias_InsertParameters} from './mb_genre_alias'
import MbGenreAliasType, {MbGenreAliasType_InsertParameters} from './mb_genre_alias_type'
import MbLGenreGenre, {MbLGenreGenre_InsertParameters} from './mb_l_genre_genre'
import MbLink, {MbLink_InsertParameters} from './mb_link'
import MbLinkType, {MbLinkType_InsertParameters} from './mb_link_type'
import MbTag, {MbTag_InsertParameters} from './mb_tag'
import Performance, {Performance_InsertParameters} from './performance'
import Song, {Song_InsertParameters} from './song'
import Week, {Week_InsertParameters} from './week'
import WeeklyBuzz, {WeeklyBuzz_InsertParameters} from './weekly_buzz'

interface DatabaseSchema {
  atdatabases_migrations_applied: {record: AtdatabasesMigrationsApplied, insert: AtdatabasesMigrationsApplied_InsertParameters};
  atdatabases_migrations_version: {record: AtdatabasesMigrationsVersion, insert: AtdatabasesMigrationsVersion_InsertParameters};
  band: {record: Band, insert: Band_InsertParameters};
  battle: {record: Battle, insert: Battle_InsertParameters};
  entry: {record: Entry, insert: Entry_InsertParameters};
  mb_genre: {record: MbGenre, insert: MbGenre_InsertParameters};
  mb_genre_alias: {record: MbGenreAlias, insert: MbGenreAlias_InsertParameters};
  mb_genre_alias_type: {record: MbGenreAliasType, insert: MbGenreAliasType_InsertParameters};
  mb_l_genre_genre: {record: MbLGenreGenre, insert: MbLGenreGenre_InsertParameters};
  mb_link: {record: MbLink, insert: MbLink_InsertParameters};
  mb_link_type: {record: MbLinkType, insert: MbLinkType_InsertParameters};
  mb_tag: {record: MbTag, insert: MbTag_InsertParameters};
  performance: {record: Performance, insert: Performance_InsertParameters};
  song: {record: Song, insert: Song_InsertParameters};
  week: {record: Week, insert: Week_InsertParameters};
  weekly_buzz: {record: WeeklyBuzz, insert: WeeklyBuzz_InsertParameters};
}
export default DatabaseSchema;

function serializeValue(_tableName: string, _columnName: string, value: unknown): unknown {
  return value;
}
export {serializeValue}

export type {
  AtdatabasesMigrationsApplied,
  AtdatabasesMigrationsApplied_InsertParameters,
  AtdatabasesMigrationsVersion,
  AtdatabasesMigrationsVersion_InsertParameters,
  Band,
  Band_InsertParameters,
  Battle,
  Battle_InsertParameters,
  Entry,
  Entry_InsertParameters,
  MbGenre,
  MbGenreAlias,
  MbGenreAliasType,
  MbGenreAliasType_InsertParameters,
  MbGenreAlias_InsertParameters,
  MbGenre_InsertParameters,
  MbLGenreGenre,
  MbLGenreGenre_InsertParameters,
  MbLink,
  MbLinkType,
  MbLinkType_InsertParameters,
  MbLink_InsertParameters,
  MbTag,
  MbTag_InsertParameters,
  Performance,
  Performance_InsertParameters,
  Song,
  Song_InsertParameters,
  Week,
  Week_InsertParameters,
  WeeklyBuzz,
  WeeklyBuzz_InsertParameters,
}
