/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: FmGhaHMNmRxeWrUo3aJxW2QhJvyNn4iYx7lS8UkgIRuvQ6ofiHlQKKuLmDGDjHNk2r7xO17nAvat6cfsNVJCpQ==
 */

/* eslint-disable */
// tslint:disable

import Band, {Band_InsertParameters} from './band'
import Battle, {Battle_InsertParameters} from './battle'
import Entry, {Entry_InsertParameters} from './entry'
import Performance, {Performance_InsertParameters} from './performance'
import Song, {Song_InsertParameters} from './song'
import Week, {Week_InsertParameters} from './week'
import WeeklyBuzz, {WeeklyBuzz_InsertParameters} from './weekly_buzz'

interface DatabaseSchema {
  band: {record: Band, insert: Band_InsertParameters};
  battle: {record: Battle, insert: Battle_InsertParameters};
  entry: {record: Entry, insert: Entry_InsertParameters};
  performance: {record: Performance, insert: Performance_InsertParameters};
  song: {record: Song, insert: Song_InsertParameters};
  week: {record: Week, insert: Week_InsertParameters};
  weekly_buzz: {record: WeeklyBuzz, insert: WeeklyBuzz_InsertParameters};
}
export default DatabaseSchema;

function serializeValue(_tableName: string, _columnName: string, value: unknown): unknown {
  return value;
}
export {serializeValue}

export type {
  Band,
  Band_InsertParameters,
  Battle,
  Battle_InsertParameters,
  Entry,
  Entry_InsertParameters,
  Performance,
  Performance_InsertParameters,
  Song,
  Song_InsertParameters,
  Week,
  Week_InsertParameters,
  WeeklyBuzz,
  WeeklyBuzz_InsertParameters,
}
