/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: i7qfMy3pvPPu1PlZtMBbW4uuD+ryqQAs3PiEbjHC5/WUrtJb6pNPCbK1gR6x6sLPZlNYwu2mwGRRlVt8BVaPOw==
 */

/* eslint-disable */
// tslint:disable

import MbGenre from './mb_genre'
import MbGenreAliasType from './mb_genre_alias_type'

interface MbGenreAlias {
  begin_date_day: (number) | null
  begin_date_month: (number) | null
  begin_date_year: (number) | null
  edits_pending: number
  end_date_day: (number) | null
  end_date_month: (number) | null
  end_date_year: (number) | null
  ended: boolean
  genre: MbGenre['id']
  /**
   * @default nextval('mb_genre_alias_id_seq'::regclass)
   */
  id: number & {readonly __brand?: 'mb_genre_alias_id'}
  last_updated: Date
  locale: (string) | null
  name: string
  primary_for_locale: boolean
  sort_name: string
  type: (MbGenreAliasType['id']) | null
}
export default MbGenreAlias;

interface MbGenreAlias_InsertParameters {
  begin_date_day?: (number) | null
  begin_date_month?: (number) | null
  begin_date_year?: (number) | null
  edits_pending: number
  end_date_day?: (number) | null
  end_date_month?: (number) | null
  end_date_year?: (number) | null
  ended: boolean
  genre: MbGenre['id']
  /**
   * @default nextval('mb_genre_alias_id_seq'::regclass)
   */
  id?: number & {readonly __brand?: 'mb_genre_alias_id'}
  last_updated: Date
  locale?: (string) | null
  name: string
  primary_for_locale: boolean
  sort_name: string
  type?: (MbGenreAliasType['id']) | null
}
export type {MbGenreAlias_InsertParameters}
