/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: Hi+hSyjzBBdNzxV0VIg3zZMqRZ43DkH0h7conrR/LiyoxmZDgDOVXhmIChO212zqvyP5mIxvK0wXlfG1XbyE8Q==
 */

/* eslint-disable */
// tslint:disable

interface MbGenreAliasType {
  child_order: number
  description: (string) | null
  gid: string
  /**
   * @default nextval('mb_genre_alias_type_id_seq'::regclass)
   */
  id: number & {readonly __brand?: 'mb_genre_alias_type_id'}
  name: string
  parent: (number) | null
}
export default MbGenreAliasType;

interface MbGenreAliasType_InsertParameters {
  child_order: number
  description?: (string) | null
  gid: string
  /**
   * @default nextval('mb_genre_alias_type_id_seq'::regclass)
   */
  id?: number & {readonly __brand?: 'mb_genre_alias_type_id'}
  name: string
  parent?: (number) | null
}
export type {MbGenreAliasType_InsertParameters}
