/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: vlRaqA5GEEA3ad6LrmggTmmtIwsrv31unXQcSIwCWg3sBtPlxREPCae/W0KzbU2JfN9vWxV33uqA2dgLM10IoA==
 */

/* eslint-disable */
// tslint:disable

import MbLinkType from './mb_link_type'

interface MbLink {
  attribute_count: number
  begin_date_day: (number) | null
  begin_date_month: (number) | null
  begin_date_year: (number) | null
  created: Date
  end_date_day: (number) | null
  end_date_month: (number) | null
  end_date_year: (number) | null
  ended: boolean
  /**
   * @default nextval('mb_link_id_seq'::regclass)
   */
  id: number & {readonly __brand?: 'mb_link_id'}
  link_type: MbLinkType['id']
}
export default MbLink;

interface MbLink_InsertParameters {
  attribute_count: number
  begin_date_day?: (number) | null
  begin_date_month?: (number) | null
  begin_date_year?: (number) | null
  created: Date
  end_date_day?: (number) | null
  end_date_month?: (number) | null
  end_date_year?: (number) | null
  ended: boolean
  /**
   * @default nextval('mb_link_id_seq'::regclass)
   */
  id?: number & {readonly __brand?: 'mb_link_id'}
  link_type: MbLinkType['id']
}
export type {MbLink_InsertParameters}
