/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: jTn7q2xqKCZe44meuY6sP/ex0jEule8m0W3uxjjE9x/uG1FV9RjngaPKZQlGvKLpB7TYVvIpOejCYU4e/YRFkA==
 */

/* eslint-disable */
// tslint:disable

interface MbLinkType {
  child_order: number
  description: string
  entity0_cardinality: number
  entity1_cardinality: number
  entity_type0: string
  entity_type1: string
  gid: string
  has_dates: boolean
  /**
   * @default nextval('mb_link_type_id_seq'::regclass)
   */
  id: number & {readonly __brand?: 'mb_link_type_id'}
  is_deprecated: boolean
  last_updated: Date
  link_phrase: string
  long_link_phrase: string
  name: string
  parent: (number) | null
  priority: number
  reverse_link_phrase: string
}
export default MbLinkType;

interface MbLinkType_InsertParameters {
  child_order: number
  description: string
  entity0_cardinality: number
  entity1_cardinality: number
  entity_type0: string
  entity_type1: string
  gid: string
  has_dates: boolean
  /**
   * @default nextval('mb_link_type_id_seq'::regclass)
   */
  id?: number & {readonly __brand?: 'mb_link_type_id'}
  is_deprecated: boolean
  last_updated: Date
  link_phrase: string
  long_link_phrase: string
  name: string
  parent?: (number) | null
  priority: number
  reverse_link_phrase: string
}
export type {MbLinkType_InsertParameters}
