/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: tsh7cPg/RcQm3WCtKbQcjck2gemFmvgU+0S3AdncwoRhYTKlbW6+WKLy3z9U0wekn6/z+rfUqdbO9pkMPN1uTw==
 */

/* eslint-disable */
// tslint:disable

import Band from './band'

interface Song {
  band_id: Band['id']
  /**
   * @default nextval('song_id_seq'::regclass)
   */
  id: number & {readonly __brand?: 'song_id'}
  name: string
}
export default Song;

interface Song_InsertParameters {
  band_id: Band['id']
  /**
   * @default nextval('song_id_seq'::regclass)
   */
  id?: number & {readonly __brand?: 'song_id'}
  name: string
}
export type {Song_InsertParameters}
