/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: 1ZJ+XlHCXFdlm2JQ2Lmox9E/Ke6u1Gxjz2fZhr8rVl+dBHabmuhjzRanjUHK6WCjAPrOpc3cV03+THAhWtRfQA==
 */

/* eslint-disable */
// tslint:disable

interface Week {
  /**
   * @default nextval('week_id_seq'::regclass)
   */
  id: number & {readonly __brand?: 'week_id'}
}
export default Week;

interface Week_InsertParameters {
  /**
   * @default nextval('week_id_seq'::regclass)
   */
  id?: number & {readonly __brand?: 'week_id'}
}
export type {Week_InsertParameters}
