/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: p29fa66D7W1Gg/Zz/cHBX/YQIosEOuGMJKmtDxJsZyvWTKcr5v2hgKOfNdPGDVXK66nSM4x+fALJ2nTUzVJTOg==
 */

/* eslint-disable */
// tslint:disable

import Band from './band'
import Week from './week'

interface WeeklyBuzz {
  band_id: Band['id']
  /**
   * @default 0
   */
  buzz: number
  week_id: Week['id']
}
export default WeeklyBuzz;

interface WeeklyBuzz_InsertParameters {
  band_id: Band['id']
  /**
   * @default 0
   */
  buzz?: number
  week_id: Week['id']
}
export type {WeeklyBuzz_InsertParameters}
